timeout = "1200s"
baseURL = 'https://the-exposure.alif4chan.workers.dev/'
languageCode = 'en-us'
description = "Personal film photography portfolio of M. Alif Farchan"
title = 'The Exposure'
disableKinds = ["section", "taxonomy", "term", "home"]
enableRobotsTXT = true

[module]
    [[module.imports]]
    path = "github.com/Sped0n/bridget/v2"

[caches]
  [caches.images]
    dir = ':cacheDir/images'